export type Difficulty = "easy" | "medium" | "hard";
export type Track = "fundamentals" | "oop" | "dsa";

export interface TestCase { input: string; expected: string; }

export interface TraceStep {
  line: number;
  variables: Record<string, string | number | boolean>;
  note: string;
}

export interface Problem {
  id: string;
  track: Track;
  title: string;
  description: string;
  difficulty: Difficulty;
  points: number;
  tags: string[];
  starterCode: string;
  testCases: TestCase[];
  hints: string[];
}

export const PROBLEMS: Problem[] = [
  // ── FUNDAMENTALS ────────────────────────────────────────────────
  {
    id: "f-001", track: "fundamentals", difficulty: "easy", points: 10,
    tags: ["arrays", "loops"],
    title: "Sum of Array",
    description: "Given an array of N integers, print the sum of all elements.\n\n**Input:** First line contains N. Second line contains N space-separated integers.\n**Output:** Print the sum.",
    starterCode: `#include<bits/stdc++.h>\nusing namespace std;\nint main(){\n    int n; cin>>n;\n    // your code here\n    return 0;\n}`,
    testCases: [{ input: "5\n1 2 3 4 5", expected: "15" }, { input: "3\n10 20 30", expected: "60" }],
    hints: ["Use a loop to accumulate the sum", "Initialize sum = 0 before the loop"],
  },
  {
    id: "f-002", track: "fundamentals", difficulty: "easy", points: 10,
    tags: ["arrays", "max"],
    title: "Maximum Element",
    description: "Find and print the maximum element in an array of N integers.\n\n**Input:** First line N, second line N integers.\n**Output:** The maximum integer.",
    starterCode: `#include<bits/stdc++.h>\nusing namespace std;\nint main(){\n    int n; cin>>n;\n    // your code here\n    return 0;\n}`,
    testCases: [{ input: "5\n3 1 4 1 5", expected: "5" }, { input: "4\n10 2 33 4", expected: "33" }],
    hints: ["Track the maximum as you iterate", "Or use std::max_element"],
  },
  {
    id: "f-003", track: "fundamentals", difficulty: "easy", points: 10,
    tags: ["strings"],
    title: "Reverse a String",
    description: "Reverse a given string and print it.\n\n**Input:** A single string (no spaces).\n**Output:** The reversed string.",
    starterCode: `#include<bits/stdc++.h>\nusing namespace std;\nint main(){\n    string s; cin>>s;\n    // your code here\n    return 0;\n}`,
    testCases: [{ input: "hello", expected: "olleh" }, { input: "abcde", expected: "edcba" }],
    hints: ["Use two-pointer technique", "Or call std::reverse(s.begin(), s.end())"],
  },
  {
    id: "f-004", track: "fundamentals", difficulty: "easy", points: 10,
    tags: ["recursion"],
    title: "Factorial",
    description: "Compute N! using recursion.\n\n**Input:** Single integer N (0 ≤ N ≤ 12).\n**Output:** N!",
    starterCode: `#include<bits/stdc++.h>\nusing namespace std;\nlong long fact(int n){\n    // your code here\n}\nint main(){\n    int n; cin>>n;\n    cout<<fact(n)<<endl;\n    return 0;\n}`,
    testCases: [{ input: "5", expected: "120" }, { input: "0", expected: "1" }, { input: "10", expected: "3628800" }],
    hints: ["Base case: fact(0) = 1", "Recursive case: n * fact(n-1)"],
  },
  {
    id: "f-005", track: "fundamentals", difficulty: "easy", points: 10,
    tags: ["recursion", "fibonacci"],
    title: "Fibonacci Number",
    description: "Return the N-th Fibonacci number (0-indexed: F(0)=0, F(1)=1).\n\n**Input:** Single integer N.\n**Output:** F(N).",
    starterCode: `#include<bits/stdc++.h>\nusing namespace std;\nlong long fib(int n){\n    // your code here\n}\nint main(){\n    int n; cin>>n;\n    cout<<fib(n)<<endl;\n    return 0;\n}`,
    testCases: [{ input: "6", expected: "8" }, { input: "0", expected: "0" }, { input: "10", expected: "55" }],
    hints: ["Base cases: fib(0)=0, fib(1)=1", "fib(n) = fib(n-1) + fib(n-2)"],
  },
  {
    id: "f-006", track: "fundamentals", difficulty: "medium", points: 20,
    tags: ["pointers", "swap"],
    title: "Swap Using Pointers",
    description: "Write a function `swap(int* a, int* b)` that swaps two integers using pointers. Read two integers, swap them, print them space-separated.\n\n**Input:** Two integers a and b.\n**Output:** b a (after swap).",
    starterCode: `#include<bits/stdc++.h>\nusing namespace std;\nvoid swap(int* a, int* b){\n    // your code here\n}\nint main(){\n    int a, b; cin>>a>>b;\n    swap(&a, &b);\n    cout<<a<<\" \"<<b<<endl;\n    return 0;\n}`,
    testCases: [{ input: "3 7", expected: "7 3" }, { input: "100 200", expected: "200 100" }],
    hints: ["Use a temporary variable", "Dereference: *a, *b to access values"],
  },
  {
    id: "f-007", track: "fundamentals", difficulty: "medium", points: 20,
    tags: ["arrays", "sorting"],
    title: "Bubble Sort",
    description: "Implement bubble sort and print the sorted array.\n\n**Input:** N, then N integers.\n**Output:** Sorted array space-separated.",
    starterCode: `#include<bits/stdc++.h>\nusing namespace std;\nint main(){\n    int n; cin>>n;\n    vector<int> a(n);\n    for(auto& x:a) cin>>x;\n    // bubble sort here\n    for(auto x:a) cout<<x<<\" \";\n    return 0;\n}`,
    testCases: [{ input: "5\n5 3 1 4 2", expected: "1 2 3 4 5 " }, { input: "3\n9 1 5", expected: "1 5 9 " }],
    hints: ["Outer loop n-1 passes", "Inner loop compares adjacent elements"],
  },
  {
    id: "f-008", track: "fundamentals", difficulty: "medium", points: 20,
    tags: ["strings", "palindrome"],
    title: "Palindrome Check",
    description: "Check if a string is a palindrome. Print 'YES' or 'NO'.\n\n**Input:** A string.\n**Output:** YES or NO.",
    starterCode: `#include<bits/stdc++.h>\nusing namespace std;\nint main(){\n    string s; cin>>s;\n    // your code here\n    return 0;\n}`,
    testCases: [{ input: "racecar", expected: "YES" }, { input: "hello", expected: "NO" }, { input: "madam", expected: "YES" }],
    hints: ["Compare s with its reverse", "Two pointers: one from start, one from end"],
  },
  {
    id: "f-009", track: "fundamentals", difficulty: "medium", points: 20,
    tags: ["recursion", "binary search"],
    title: "Recursive Binary Search",
    description: "Implement binary search recursively. Print the 0-based index of the target, or -1 if not found.\n\n**Input:** N, then N sorted integers, then target T.\n**Output:** Index or -1.",
    starterCode: `#include<bits/stdc++.h>\nusing namespace std;\nint bsearch(vector<int>& a, int lo, int hi, int t){\n    // your code here\n}\nint main(){\n    int n; cin>>n;\n    vector<int> a(n);\n    for(auto& x:a) cin>>x;\n    int t; cin>>t;\n    cout<<bsearch(a,0,n-1,t)<<endl;\n    return 0;\n}`,
    testCases: [{ input: "5\n1 3 5 7 9\n7", expected: "3" }, { input: "4\n2 4 6 8\n5", expected: "-1" }],
    hints: ["Base case: lo > hi → return -1", "mid = (lo+hi)/2"],
  },
  {
    id: "f-010", track: "fundamentals", difficulty: "medium", points: 20,
    tags: ["pointers", "arrays"],
    title: "Array Sum via Pointer",
    description: "Compute the sum of an array using pointer arithmetic (no index notation).\n\n**Input:** N, then N integers.\n**Output:** Sum.",
    starterCode: `#include<bits/stdc++.h>\nusing namespace std;\nint main(){\n    int n; cin>>n;\n    int a[100];\n    for(int i=0;i<n;i++) cin>>a[i];\n    int sum=0;\n    int* p = a;\n    // use pointer arithmetic\n    cout<<sum<<endl;\n    return 0;\n}`,
    testCases: [{ input: "4\n1 2 3 4", expected: "10" }, { input: "3\n5 5 5", expected: "15" }],
    hints: ["*(p+i) accesses element i", "Increment p using p++"],
  },
  {
    id: "f-011", track: "fundamentals", difficulty: "hard", points: 30,
    tags: ["recursion", "towers of hanoi"],
    title: "Towers of Hanoi",
    description: "Print the moves to solve Tower of Hanoi with N disks (from rod A to rod C using rod B). Format: 'Move disk X from A to C'.\n\n**Input:** N.\n**Output:** All moves.",
    starterCode: `#include<bits/stdc++.h>\nusing namespace std;\nvoid hanoi(int n, char from, char to, char aux){\n    // your code here\n}\nint main(){\n    int n; cin>>n;\n    hanoi(n,'A','C','B');\n    return 0;\n}`,
    testCases: [{ input: "2", expected: "Move disk 1 from A to B\nMove disk 2 from A to C\nMove disk 1 from B to C" }],
    hints: ["Recursively move n-1 disks to aux", "Move disk n to destination", "Recursively move n-1 disks from aux to destination"],
  },
  {
    id: "f-012", track: "fundamentals", difficulty: "hard", points: 30,
    tags: ["strings", "anagram"],
    title: "Anagram Check",
    description: "Determine if two strings are anagrams. Print 'YES' or 'NO'.\n\n**Input:** Two strings on separate lines.\n**Output:** YES or NO.",
    starterCode: `#include<bits/stdc++.h>\nusing namespace std;\nint main(){\n    string a, b; cin>>a>>b;\n    // your code here\n    return 0;\n}`,
    testCases: [{ input: "listen\nsilent", expected: "YES" }, { input: "hello\nworld", expected: "NO" }],
    hints: ["Sort both strings and compare", "Or use frequency count array"],
  },
  {
    id: "f-013", track: "fundamentals", difficulty: "hard", points: 30,
    tags: ["recursion", "permutations"],
    title: "String Permutations",
    description: "Print all permutations of a string in lexicographic order.\n\n**Input:** A string of distinct lowercase letters.\n**Output:** One permutation per line.",
    starterCode: `#include<bits/stdc++.h>\nusing namespace std;\nint main(){\n    string s; cin>>s;\n    sort(s.begin(),s.end());\n    do{\n        cout<<s<<\"\\n\";\n    }while(next_permutation(s.begin(),s.end()));\n    return 0;\n}`,
    testCases: [{ input: "abc", expected: "abc\nabcb\nacb\nbac\nbca\ncab\ncba" }, { input: "ab", expected: "ab\nba" }],
    hints: ["Use next_permutation after sorting", "Or implement recursive backtracking"],
  },
  {
    id: "f-014", track: "fundamentals", difficulty: "easy", points: 10,
    tags: ["arrays", "two-pointer"],
    title: "Two Sum",
    description: "Find two indices i, j (i < j) such that arr[i] + arr[j] = target. Print the indices or -1 -1 if none.\n\n**Input:** N, then N integers, then target.\n**Output:** i j or -1 -1.",
    starterCode: `#include<bits/stdc++.h>\nusing namespace std;\nint main(){\n    int n; cin>>n;\n    vector<int> a(n);\n    for(auto& x:a) cin>>x;\n    int t; cin>>t;\n    // your code here\n    return 0;\n}`,
    testCases: [{ input: "5\n2 7 11 15 1\n9", expected: "0 1" }, { input: "3\n1 2 3\n7", expected: "-1 -1" }],
    hints: ["Brute force: check all pairs O(n²)", "Use a hash map for O(n)"],
  },
  {
    id: "f-015", track: "fundamentals", difficulty: "medium", points: 20,
    tags: ["arrays", "prefix sum"],
    title: "Subarray with Given Sum",
    description: "Find a contiguous subarray that sums to S. Print the 1-based start and end indices, or -1 if none.\n\n**Input:** N, then N non-negative integers, then S.\n**Output:** start end or -1.",
    starterCode: `#include<bits/stdc++.h>\nusing namespace std;\nint main(){\n    int n; cin>>n;\n    vector<int> a(n);\n    for(auto& x:a) cin>>x;\n    int s; cin>>s;\n    // sliding window\n    return 0;\n}`,
    testCases: [{ input: "5\n1 2 3 4 5\n9", expected: "2 4" }, { input: "3\n1 2 3\n10", expected: "-1" }],
    hints: ["Sliding window: expand right, shrink left", "Works for non-negative arrays"],
  },

  // ── OOP ─────────────────────────────────────────────────────────
  {
    id: "o-001", track: "oop", difficulty: "easy", points: 10,
    tags: ["classes", "constructors"],
    title: "Rectangle Class",
    description: "Create a `Rectangle` class with `width` and `height`. Add method `area()` and `perimeter()`. Read dimensions, print area then perimeter on separate lines.\n\n**Input:** width height.\n**Output:** area\\nperimeter.",
    starterCode: `#include<bits/stdc++.h>\nusing namespace std;\nclass Rectangle{\n    // your code here\n};\nint main(){\n    int w,h; cin>>w>>h;\n    Rectangle r(w,h);\n    cout<<r.area()<<\"\\n\"<<r.perimeter()<<\"\\n\";\n    return 0;\n}`,
    testCases: [{ input: "4 5", expected: "20\n18" }, { input: "3 3", expected: "9\n12" }],
    hints: ["Use a constructor: Rectangle(int w, int h)", "area = w*h, perimeter = 2*(w+h)"],
  },
  {
    id: "o-002", track: "oop", difficulty: "easy", points: 10,
    tags: ["classes", "encapsulation"],
    title: "Bank Account",
    description: "Model a `BankAccount` with `deposit(amount)`, `withdraw(amount)`, and `getBalance()`. Apply operations from input and print final balance.\n\n**Input:** Initial balance, then Q operations (D amount or W amount).\n**Output:** Final balance.",
    starterCode: `#include<bits/stdc++.h>\nusing namespace std;\nclass BankAccount{\n    double balance;\npublic:\n    BankAccount(double b): balance(b){}\n    // add deposit, withdraw, getBalance\n};\nint main(){\n    double b; cin>>b;\n    BankAccount acc(b);\n    int q; cin>>q;\n    while(q--){\n        char op; double amt;\n        cin>>op>>amt;\n        if(op=='D') acc.deposit(amt);\n        else acc.withdraw(amt);\n    }\n    cout<<fixed<<setprecision(2)<<acc.getBalance()<<\"\\n\";\n    return 0;\n}`,
    testCases: [{ input: "1000\n3\nD 500\nW 200\nD 100", expected: "1400.00" }],
    hints: ["Don't allow balance to go negative on withdraw", "getBalance returns private member"],
  },
  {
    id: "o-003", track: "oop", difficulty: "medium", points: 20,
    tags: ["inheritance"],
    title: "Shape Hierarchy",
    description: "Create base class `Shape` with virtual `area()`. Derive `Circle` (uses π=3.14159) and `Square`. Read type and dimensions, print area to 2 decimal places.\n\n**Input:** First line: type (circle/square). Second line: dimension.\n**Output:** area to 2dp.",
    starterCode: `#include<bits/stdc++.h>\nusing namespace std;\nclass Shape{\npublic:\n    virtual double area()=0;\n};\n// add Circle and Square\nint main(){\n    string type; cin>>type;\n    double d; cin>>d;\n    Shape* s;\n    if(type==\"circle\") s=new Circle(d);\n    else s=new Square(d);\n    cout<<fixed<<setprecision(2)<<s->area()<<\"\\n\";\n    delete s;\n    return 0;\n}`,
    testCases: [{ input: "circle\n5", expected: "78.54" }, { input: "square\n4", expected: "16.00" }],
    hints: ["Circle: area = π*r²", "Square: area = side²", "Use virtual functions for runtime polymorphism"],
  },
  {
    id: "o-004", track: "oop", difficulty: "medium", points: 20,
    tags: ["polymorphism", "virtual"],
    title: "Animal Sounds",
    description: "Create a base `Animal` with virtual `speak()`. Derive `Dog` (Woof!), `Cat` (Meow!), `Cow` (Moo!). Read N animals, call speak on each.\n\n**Input:** N, then N animal types (dog/cat/cow).\n**Output:** Each animal's sound.",
    starterCode: `#include<bits/stdc++.h>\nusing namespace std;\nclass Animal{\npublic:\n    virtual string speak()=0;\n    virtual ~Animal(){}\n};\n// derive Dog, Cat, Cow\nint main(){\n    int n; cin>>n;\n    vector<Animal*> v;\n    while(n--){\n        string t; cin>>t;\n        if(t==\"dog\") v.push_back(new Dog());\n        else if(t==\"cat\") v.push_back(new Cat());\n        else v.push_back(new Cow());\n    }\n    for(auto a:v){cout<<a->speak()<<\"\\n\"; delete a;}\n    return 0;\n}`,
    testCases: [{ input: "3\ndog\ncat\ncow", expected: "Woof!\nMeow!\nMoo!" }],
    hints: ["Pure virtual: virtual string speak() = 0", "Override in each derived class"],
  },
  {
    id: "o-005", track: "oop", difficulty: "medium", points: 20,
    tags: ["classes", "operator overloading"],
    title: "Complex Number Addition",
    description: "Create a `Complex` class with real and imaginary parts. Overload `+` operator. Read two complex numbers and print their sum.\n\n**Input:** a b (first: a+bi), then c d (second: c+di).\n**Output:** (a+c)+(b+d)i format.",
    starterCode: `#include<bits/stdc++.h>\nusing namespace std;\nclass Complex{\npublic:\n    double re, im;\n    Complex(double r=0,double i=0):re(r),im(i){}\n    // overload +\n};\nint main(){\n    double a,b,c,d;\n    cin>>a>>b>>c>>d;\n    Complex x(a,b), y(c,d);\n    Complex z = x+y;\n    cout<<z.re<<\"+\"<<z.im<<\"i\\n\";\n    return 0;\n}`,
    testCases: [{ input: "3 4 1 2", expected: "4+6i" }, { input: "0 0 5 5", expected: "5+5i" }],
    hints: ["Complex operator+(const Complex& o) { return Complex(re+o.re, im+o.im); }"],
  },
  {
    id: "o-006", track: "oop", difficulty: "hard", points: 30,
    tags: ["inheritance", "multilevel"],
    title: "Employee Hierarchy",
    description: "Create: `Person` (name), `Employee` extends Person (salary), `Manager` extends Employee (bonus). Manager's totalPay = salary + bonus. Read type and fields, print totalPay.\n\n**Input:** type (employee/manager), name, salary [bonus if manager].\n**Output:** totalPay.",
    starterCode: `#include<bits/stdc++.h>\nusing namespace std;\nclass Person{\nprotected:\n    string name;\npublic:\n    Person(string n):name(n){}\n    virtual double totalPay()=0;\n    virtual ~Person(){}\n};\n// add Employee and Manager\nint main(){\n    string type,name;\n    cin>>type>>name;\n    double salary; cin>>salary;\n    Person* p;\n    if(type==\"manager\"){\n        double bonus; cin>>bonus;\n        p=new Manager(name,salary,bonus);\n    } else p=new Employee(name,salary);\n    cout<<p->totalPay()<<\"\\n\";\n    delete p;\n    return 0;\n}`,
    testCases: [{ input: "manager Ali 50000 10000", expected: "60000" }, { input: "employee Sara 40000", expected: "40000" }],
    hints: ["Manager inherits from Employee", "Override totalPay() in each class"],
  },
  {
    id: "o-007", track: "oop", difficulty: "hard", points: 30,
    tags: ["templates", "generics"],
    title: "Generic Stack",
    description: "Implement a generic `Stack<T>` class with push, pop, top, and isEmpty. Read N integers, push them, then pop and print each.\n\n**Input:** N, then N integers.\n**Output:** Popped values one per line (LIFO order).",
    starterCode: `#include<bits/stdc++.h>\nusing namespace std;\ntemplate<typename T>\nclass Stack{\n    // your code here\n};\nint main(){\n    int n; cin>>n;\n    Stack<int> s;\n    for(int i=0;i<n;i++){int x;cin>>x;s.push(x);}\n    while(!s.isEmpty()) cout<<s.pop()<<\"\\n\";\n    return 0;\n}`,
    testCases: [{ input: "4\n1 2 3 4", expected: "4\n3\n2\n1" }],
    hints: ["Use a vector internally", "top() returns last element"],
  },
  {
    id: "o-008", track: "oop", difficulty: "easy", points: 10,
    tags: ["constructors", "destructor"],
    title: "Student GPA",
    description: "Create a `Student` class with name and grades vector. Method `gpa()` returns the average. Read N grades.\n\n**Input:** Student name, N, then N grades (0-4 scale).\n**Output:** GPA to 2dp.",
    starterCode: `#include<bits/stdc++.h>\nusing namespace std;\nclass Student{\n    string name;\n    vector<double> grades;\npublic:\n    Student(string n):name(n){}\n    void addGrade(double g){grades.push_back(g);}\n    double gpa(){\n        // your code here\n    }\n};\nint main(){\n    string name; cin>>name;\n    int n; cin>>n;\n    Student s(name);\n    for(int i=0;i<n;i++){double g;cin>>g;s.addGrade(g);}\n    cout<<fixed<<setprecision(2)<<s.gpa()<<\"\\n\";\n    return 0;\n}`,
    testCases: [{ input: "Ali 4\n3.5 4.0 3.0 3.5", expected: "3.50" }],
    hints: ["Sum all grades and divide by count"],
  },

  // ── DSA ─────────────────────────────────────────────────────────
  {
    id: "d-001", track: "dsa", difficulty: "easy", points: 10,
    tags: ["stack", "data structures"],
    title: "Balanced Parentheses",
    description: "Check if a string of brackets is balanced. Print YES or NO.\n\n**Input:** A string of (, ), [, ], {, }.\n**Output:** YES or NO.",
    starterCode: `#include<bits/stdc++.h>\nusing namespace std;\nint main(){\n    string s; cin>>s;\n    stack<char> st;\n    // your code here\n    return 0;\n}`,
    testCases: [{ input: "({[]})", expected: "YES" }, { input: "([)]", expected: "NO" }, { input: "{{}}", expected: "YES" }],
    hints: ["Push opening brackets", "For closing brackets, check if top matches"],
  },
  {
    id: "d-002", track: "dsa", difficulty: "easy", points: 10,
    tags: ["linked list"],
    title: "Reverse a Linked List",
    description: "Reverse a singly linked list and print the values.\n\n**Input:** N, then N integers (nodes in order).\n**Output:** Values reversed, space-separated.",
    starterCode: `#include<bits/stdc++.h>\nusing namespace std;\nstruct Node{ int val; Node* next; Node(int v):val(v),next(nullptr){} };\nNode* reverse(Node* head){\n    // your code here\n}\nint main(){\n    int n; cin>>n;\n    Node* head=nullptr; Node* tail=nullptr;\n    for(int i=0;i<n;i++){int x;cin>>x;Node* nd=new Node(x);if(!head)head=tail=nd;else{tail->next=nd;tail=nd;}}\n    head=reverse(head);\n    for(Node* c=head;c;c=c->next) cout<<c->val<<\" \";\n    return 0;\n}`,
    testCases: [{ input: "5\n1 2 3 4 5", expected: "5 4 3 2 1 " }],
    hints: ["Three pointers: prev, curr, next", "Iteratively reverse links"],
  },
  {
    id: "d-003", track: "dsa", difficulty: "medium", points: 20,
    tags: ["binary search tree"],
    title: "BST Insert and Inorder",
    description: "Insert N values into a BST and print the inorder traversal.\n\n**Input:** N, then N integers.\n**Output:** Inorder traversal space-separated.",
    starterCode: `#include<bits/stdc++.h>\nusing namespace std;\nstruct Node{ int val; Node *left,*right; Node(int v):val(v),left(nullptr),right(nullptr){} };\nNode* insert(Node* root, int v){\n    // your code here\n}\nvoid inorder(Node* root){\n    if(!root) return;\n    inorder(root->left);\n    cout<<root->val<<\" \";\n    inorder(root->right);\n}\nint main(){\n    int n; cin>>n;\n    Node* root=nullptr;\n    for(int i=0;i<n;i++){int x;cin>>x;root=insert(root,x);}\n    inorder(root);\n    return 0;\n}`,
    testCases: [{ input: "5\n5 3 7 1 4", expected: "1 3 4 5 7 " }],
    hints: ["If v < root->val, go left; else go right", "Inorder = left, root, right → sorted"],
  },
  {
    id: "d-004", track: "dsa", difficulty: "medium", points: 20,
    tags: ["graph", "bfs"],
    title: "BFS Shortest Path",
    description: "Find shortest path (edges) from node 0 to all nodes in an undirected graph.\n\n**Input:** N nodes, M edges, then M pairs u v. Print distances from 0.\n**Output:** N distances space-separated (-1 if unreachable).",
    starterCode: `#include<bits/stdc++.h>\nusing namespace std;\nint main(){\n    int n,m; cin>>n>>m;\n    vector<vector<int>> adj(n);\n    for(int i=0;i<m;i++){int u,v;cin>>u>>v;adj[u].push_back(v);adj[v].push_back(u);}\n    vector<int> dist(n,-1);\n    // BFS from 0\n    for(int i=0;i<n;i++) cout<<dist[i]<<\" \";\n    return 0;\n}`,
    testCases: [{ input: "4 4\n0 1\n0 2\n1 3\n2 3", expected: "0 1 1 2 " }],
    hints: ["Use a queue", "Initialize dist[0]=0, push 0", "For each neighbor not visited, dist[nb]=dist[curr]+1"],
  },
  {
    id: "d-005", track: "dsa", difficulty: "medium", points: 20,
    tags: ["dynamic programming"],
    title: "Longest Common Subsequence",
    description: "Find the length of LCS of two strings.\n\n**Input:** Two strings on separate lines.\n**Output:** LCS length.",
    starterCode: `#include<bits/stdc++.h>\nusing namespace std;\nint main(){\n    string a, b;\n    cin>>a>>b;\n    int n=a.size(), m=b.size();\n    vector<vector<int>> dp(n+1, vector<int>(m+1,0));\n    // fill dp table\n    cout<<dp[n][m]<<\"\\n\";\n    return 0;\n}`,
    testCases: [{ input: "abcde\nace", expected: "3" }, { input: "abc\nabc", expected: "3" }],
    hints: ["dp[i][j] = LCS of a[0..i-1] and b[0..j-1]", "If a[i-1]==b[j-1]: dp[i][j]=dp[i-1][j-1]+1"],
  },
  {
    id: "d-006", track: "dsa", difficulty: "hard", points: 30,
    tags: ["dynamic programming", "knapsack"],
    title: "0/1 Knapsack",
    description: "Given N items with weight and value, and a knapsack of capacity W, find the maximum value.\n\n**Input:** N W, then N lines each with weight value.\n**Output:** Maximum value.",
    starterCode: `#include<bits/stdc++.h>\nusing namespace std;\nint main(){\n    int n,W; cin>>n>>W;\n    vector<int> wt(n),val(n);\n    for(int i=0;i<n;i++) cin>>wt[i]>>val[i];\n    vector<vector<int>> dp(n+1,vector<int>(W+1,0));\n    // fill knapsack dp\n    cout<<dp[n][W]<<\"\\n\";\n    return 0;\n}`,
    testCases: [{ input: "3 50\n10 60\n20 100\n30 120", expected: "220" }],
    hints: ["dp[i][w] = max value using first i items with capacity w", "If wt[i]<=w: dp[i][w]=max(dp[i-1][w], dp[i-1][w-wt[i]]+val[i])"],
  },
  {
    id: "d-007", track: "dsa", difficulty: "hard", points: 30,
    tags: ["graph", "dfs", "cycle"],
    title: "Detect Cycle in Directed Graph",
    description: "Detect if a directed graph has a cycle. Print YES or NO.\n\n**Input:** N nodes, M edges, then M directed edges u→v.\n**Output:** YES if cycle exists, NO otherwise.",
    starterCode: `#include<bits/stdc++.h>\nusing namespace std;\nvector<vector<int>> adj;\nvector<int> color; // 0=white,1=gray,2=black\nbool dfs(int u){\n    color[u]=1;\n    for(int v:adj[u]){\n        if(color[v]==1) return true;\n        if(color[v]==0 && dfs(v)) return true;\n    }\n    color[u]=2;\n    return false;\n}\nint main(){\n    int n,m; cin>>n>>m;\n    adj.resize(n); color.assign(n,0);\n    for(int i=0;i<m;i++){int u,v;cin>>u>>v;adj[u].push_back(v);}\n    bool cycle=false;\n    for(int i=0;i<n;i++) if(!color[i] && dfs(i)){cycle=true;break;}\n    cout<<(cycle?\"YES\":\"NO\")<<\"\\n\";\n    return 0;\n}`,
    testCases: [{ input: "3 3\n0 1\n1 2\n2 0", expected: "YES" }, { input: "3 2\n0 1\n1 2", expected: "NO" }],
    hints: ["Gray = currently in DFS stack", "Back edge to gray node = cycle"],
  },
  {
    id: "d-008", track: "dsa", difficulty: "easy", points: 10,
    tags: ["queue", "data structures"],
    title: "Queue Using Two Stacks",
    description: "Implement a queue using two stacks. Process enqueue (E x) and dequeue (D) operations.\n\n**Input:** Q operations.\n**Output:** Print value for each D operation.",
    starterCode: `#include<bits/stdc++.h>\nusing namespace std;\nstack<int> s1, s2;\nvoid enqueue(int x){ s1.push(x); }\nint dequeue(){\n    if(s2.empty()) while(!s1.empty()){s2.push(s1.top());s1.pop();}\n    int val=s2.top(); s2.pop(); return val;\n}\nint main(){\n    int q; cin>>q;\n    while(q--){\n        char op; cin>>op;\n        if(op=='E'){int x;cin>>x;enqueue(x);}\n        else cout<<dequeue()<<\"\\n\";\n    }\n    return 0;\n}`,
    testCases: [{ input: "5\nE 1\nE 2\nD\nE 3\nD", expected: "1\n2" }],
    hints: ["s1 for enqueue, s2 for dequeue", "Transfer s1→s2 only when s2 is empty"],
  },
  {
    id: "d-009", track: "dsa", difficulty: "medium", points: 20,
    tags: ["heap", "priority queue"],
    title: "K Largest Elements",
    description: "Find the K largest elements in an array (print in descending order).\n\n**Input:** N K, then N integers.\n**Output:** K largest, descending, space-separated.",
    starterCode: `#include<bits/stdc++.h>\nusing namespace std;\nint main(){\n    int n,k; cin>>n>>k;\n    vector<int> a(n);\n    for(auto& x:a) cin>>x;\n    priority_queue<int> pq(a.begin(),a.end());\n    for(int i=0;i<k;i++){cout<<pq.top();pq.pop();if(i<k-1)cout<<\" \";}\n    cout<<\"\\n\";\n    return 0;\n}`,
    testCases: [{ input: "6 3\n3 2 1 5 6 4", expected: "6 5 4" }],
    hints: ["Max-heap (default priority_queue) gives largest first"],
  },
  {
    id: "d-010", track: "dsa", difficulty: "hard", points: 30,
    tags: ["segment tree"],
    title: "Range Sum Query",
    description: "Given an array, answer Q range sum queries [l, r] (1-indexed).\n\n**Input:** N, then N integers, then Q queries each with l r.\n**Output:** Sum for each query.",
    starterCode: `#include<bits/stdc++.h>\nusing namespace std;\nvector<int> tree;\nvoid build(vector<int>& a, int node, int lo, int hi){\n    if(lo==hi){tree[node]=a[lo];return;}\n    int mid=(lo+hi)/2;\n    build(a,2*node,lo,mid);\n    build(a,2*node+1,mid+1,hi);\n    tree[node]=tree[2*node]+tree[2*node+1];\n}\nint query(int node,int lo,int hi,int l,int r){\n    if(r<lo||hi<l) return 0;\n    if(l<=lo&&hi<=r) return tree[node];\n    int mid=(lo+hi)/2;\n    return query(2*node,lo,mid,l,r)+query(2*node+1,mid+1,hi,l,r);\n}\nint main(){\n    int n; cin>>n;\n    vector<int> a(n+1);\n    for(int i=1;i<=n;i++) cin>>a[i];\n    tree.resize(4*n);\n    build(a,1,1,n);\n    int q; cin>>q;\n    while(q--){int l,r;cin>>l>>r;cout<<query(1,1,n,l,r)<<\"\\n\";}\n    return 0;\n}`,
    testCases: [{ input: "5\n1 2 3 4 5\n3\n1 3\n2 5\n1 5", expected: "6\n14\n15" }],
    hints: ["Build segment tree recursively", "query handles out-of-range with return 0"],
  },
  {
    id: "d-011", track: "dsa", difficulty: "medium", points: 20,
    tags: ["hashing", "two sum"],
    title: "Pair with Target Sum (Hash Map)",
    description: "Find if any pair sums to target using O(n) time. Print YES or NO.\n\n**Input:** N, then N integers, then target.\n**Output:** YES or NO.",
    starterCode: `#include<bits/stdc++.h>\nusing namespace std;\nint main(){\n    int n; cin>>n;\n    vector<int> a(n);\n    for(auto& x:a) cin>>x;\n    int t; cin>>t;\n    unordered_set<int> seen;\n    // your code here\n    return 0;\n}`,
    testCases: [{ input: "5\n1 4 45 6 10\n16", expected: "YES" }, { input: "3\n1 2 3\n10", expected: "NO" }],
    hints: ["For each x, check if (t-x) is in the set", "Insert x into set after checking"],
  },
  {
    id: "d-012", track: "dsa", difficulty: "hard", points: 30,
    tags: ["trie"],
    title: "Word Search Trie",
    description: "Insert N words into a Trie. For Q queries, check if the word exists. Print YES or NO for each.\n\n**Input:** N words, Q queries.\n**Output:** YES/NO per query.",
    starterCode: `#include<bits/stdc++.h>\nusing namespace std;\nstruct TrieNode{\n    TrieNode* children[26]={nullptr};\n    bool isEnd=false;\n};\nstruct Trie{\n    TrieNode* root=new TrieNode();\n    void insert(string s){\n        // your code here\n    }\n    bool search(string s){\n        // your code here\n    }\n};\nint main(){\n    int n; cin>>n;\n    Trie t;\n    for(int i=0;i<n;i++){string s;cin>>s;t.insert(s);}\n    int q; cin>>q;\n    while(q--){string s;cin>>s;cout<<(t.search(s)?\"YES\":\"NO\")<<\"\\n\";}\n    return 0;\n}`,
    testCases: [{ input: "3\napple\napp\nban\n2\napple\nbanana", expected: "YES\nNO" }],
    hints: ["Each node has 26 children for a-z", "s[i]-'a' gives the index"],
  },
];

export const TRACKS = [
  {
    id: "fundamentals" as Track,
    label: "Programming Fundamentals",
    icon: "FND",
    color: "from-[rgb(var(--hue-a)/0.18)] to-[rgb(var(--hue-a)/0.06)]",
    borderColor: "border-[rgb(var(--hue-a)/0.22)]",
    accentColor: "text-[rgb(var(--hue-a))]",
    topics: ["Arrays", "Pointers", "Recursion", "Strings"],
    description: "Master the core building blocks: arrays, pointers, recursion, and string manipulation.",
  },
  {
    id: "oop" as Track,
    label: "Object-Oriented Programming",
    icon: "OOP",
    color: "from-[rgb(var(--hue-e)/0.18)] to-[rgb(var(--hue-d)/0.06)]",
    borderColor: "border-[rgb(var(--hue-e)/0.22)]",
    accentColor: "text-[rgb(var(--hue-e))]",
    topics: ["Classes", "Inheritance", "Polymorphism", "Templates"],
    description: "Build robust software using OOP principles: encapsulation, inheritance, and polymorphism.",
  },
  {
    id: "dsa" as Track,
    label: "Data Structures & Algorithms",
    icon: "DSA",
    color: "from-[rgb(var(--success)/0.18)] to-[rgb(var(--hue-f)/0.06)]",
    borderColor: "border-[rgb(var(--success)/0.22)]",
    accentColor: "text-[rgb(var(--success))]",
    topics: ["Linked Lists", "Trees", "Graphs", "Dynamic Programming"],
    description: "Conquer complex problems with efficient data structures and algorithmic techniques.",
  },
];

export const DRY_RUN_SNIPPETS = [
  {
    id: "dr-001", track: "fundamentals" as Track, difficulty: "easy" as Difficulty, points: 5,
    code: `int x = 5, y = 3;\nint z = x++ + --y;\ncout << x << " " << y << " " << z;`,
    correctOutput: "6 2 7",
    explanation: "x++ returns 5 then increments (x=6). --y decrements first (y=2). z = 5+2 = 7.",
  },
  {
    id: "dr-002", track: "fundamentals" as Track, difficulty: "easy" as Difficulty, points: 5,
    code: `int a[] = {10, 20, 30};\nint* p = a;\np++;\ncout << *p << " " << *(p+1);`,
    correctOutput: "20 30",
    explanation: "p starts at a[0]. p++ moves to a[1]=20. *(p+1) is a[2]=30.",
  },
  {
    id: "dr-003", track: "fundamentals" as Track, difficulty: "medium" as Difficulty, points: 10,
    code: `int f(int n){\n  if(n<=1) return n;\n  return f(n-1)+f(n-2);\n}\ncout << f(5);`,
    correctOutput: "5",
    explanation: "f(5)=f(4)+f(3)=3+2=5. Fibonacci sequence.",
  },
  {
    id: "dr-004", track: "oop" as Track, difficulty: "medium" as Difficulty, points: 10,
    code: `class A{ public: virtual void f(){ cout<<"A"; } };\nclass B:public A{ public: void f(){ cout<<"B"; } };\nA* p = new B();\np->f();`,
    correctOutput: "B",
    explanation: "Virtual dispatch: p points to B object, so B::f() is called.",
  },
  {
    id: "dr-005", track: "dsa" as Track, difficulty: "medium" as Difficulty, points: 10,
    code: `stack<int> s;\ns.push(1); s.push(2); s.push(3);\nwhile(!s.empty()){\n  cout<<s.top()<<\" \";\n  s.pop();\n}`,
    correctOutput: "3 2 1 ",
    explanation: "Stack is LIFO. Push 1,2,3. Pop order: 3,2,1.",
  },
  {
    id: "dr-006", track: "fundamentals" as Track, difficulty: "hard" as Difficulty, points: 15,
    code: `int arr[] = {5,4,3,2,1};\nint n=5;\nfor(int i=0;i<n/2;i++)\n  swap(arr[i],arr[n-1-i]);\nfor(int x:arr) cout<<x<<\" \";`,
    correctOutput: "1 2 3 4 5 ",
    explanation: "Reverses array in-place by swapping from both ends.",
  },
  {
    id: "dr-007", track: "oop" as Track, difficulty: "easy" as Difficulty, points: 5,
    code: `class Counter{\n  int n=0;\npublic:\n  void inc(){ n++; }\n  int get(){ return n; }\n};\nCounter c;\nc.inc(); c.inc(); c.inc();\ncout << c.get();`,
    correctOutput: "3",
    explanation: "inc() is called 3 times, get() returns 3.",
  },
  {
    id: "dr-008", track: "dsa" as Track, difficulty: "hard" as Difficulty, points: 15,
    code: `vector<int> dp(5,0);\ndp[0]=1;\nfor(int i=1;i<5;i++)\n  dp[i]=dp[i-1]*2;\nfor(int x:dp) cout<<x<<\" \";`,
    correctOutput: "1 2 4 8 16 ",
    explanation: "dp[i] = 2^i. Powers of 2 from 2^0 to 2^4.",
    traceSteps: [
      { line: 1, variables: { "dp": "[0,0,0,0,0]" }, note: "dp initialized to 5 zeros" },
      { line: 2, variables: { "dp[0]": 1, "dp": "[1,0,0,0,0]" }, note: "dp[0] = 1" },
      { line: 3, variables: { i: 1, "dp[1]": 2, "dp": "[1,2,0,0,0]" }, note: "i=1: dp[1]=dp[0]*2=2" },
      { line: 3, variables: { i: 2, "dp[2]": 4, "dp": "[1,2,4,0,0]" }, note: "i=2: dp[2]=dp[1]*2=4" },
      { line: 3, variables: { i: 3, "dp[3]": 8, "dp": "[1,2,4,8,0]" }, note: "i=3: dp[3]=8" },
      { line: 3, variables: { i: 4, "dp[4]": 16, "dp": "[1,2,4,8,16]" }, note: "i=4: dp[4]=16" },
      { line: 4, variables: { output: "1 2 4 8 16 " }, note: "Print all elements" },
    ],
  },
  {
    id: "dr-009", track: "fundamentals" as Track, difficulty: "medium" as Difficulty, points: 10,
    code: `int a=10, b=3;\ncout << a/b << " ";\ncout << a%b << " ";\ncout << (a&b);`,
    correctOutput: "3 1 2",
    explanation: "10/3=3 (integer), 10%3=1, 10&3 = 1010&0011 = 0010 = 2.",
    traceSteps: [
      { line: 1, variables: { a: 10, b: 3 }, note: "a=10, b=3 initialized" },
      { line: 2, variables: { "a/b": 3 }, note: "Integer division: 10/3 = 3" },
      { line: 3, variables: { "a%b": 1 }, note: "Modulo: 10%3 = 1" },
      { line: 4, variables: { "a&b": 2 }, note: "Bitwise AND: 1010 & 0011 = 0010 = 2" },
    ],
  },
  {
    id: "dr-010", track: "oop" as Track, difficulty: "hard" as Difficulty, points: 15,
    code: `class Base{\npublic:\n  Base(){ cout<<"B"; }\n  ~Base(){ cout<<"~B"; }\n};\nclass Der:public Base{\npublic:\n  Der(){ cout<<"D"; }\n  ~Der(){ cout<<"~D"; }\n};\n{\n  Der d;\n}`,
    correctOutput: "BD~D~B",
    explanation: "Base constructor first (B), then Derived (D). Destructors in reverse: ~D then ~B.",
    traceSteps: [
      { line: 11, variables: { scope: "enter" }, note: "Enter block, create Der d" },
      { line: 3, variables: { output: "B" }, note: "Base() constructor called first" },
      { line: 9, variables: { output: "BD" }, note: "Der() constructor called after Base" },
      { line: 12, variables: { scope: "exit" }, note: "Block ends, destruction in reverse order" },
      { line: 10, variables: { output: "BD~D" }, note: "~Der() called first" },
      { line: 4, variables: { output: "BD~D~B" }, note: "~Base() called last" },
    ],
  },
];

// ── Additional 20+ problems to reach 50+ ─────────────────────────
export const EXTRA_PROBLEMS: Problem[] = [
  // FUNDAMENTALS extras
  {
    id: "f-016", track: "fundamentals", difficulty: "easy", points: 10,
    tags: ["arrays", "counting"],
    title: "Count Even and Odd",
    description: "Count even and odd numbers in an array.\n\n**Input:** N, then N integers.\n**Output:** Two numbers: count_even count_odd.",
    starterCode: `#include<bits/stdc++.h>\nusing namespace std;\nint main(){\n    int n; cin>>n;\n    int ev=0,od=0;\n    for(int i=0;i<n;i++){int x;cin>>x;if(x%2==0)ev++;else od++;}\n    cout<<ev<<\" \"<<od<<endl;\n    return 0;\n}`,
    testCases: [{ input: "6\n1 2 3 4 5 6", expected: "3 3" }],
    hints: ["x%2==0 means even"],
  },
  {
    id: "f-017", track: "fundamentals", difficulty: "easy", points: 10,
    tags: ["math", "prime"],
    title: "Prime Check",
    description: "Check if N is prime. Print YES or NO.\n\n**Input:** Integer N.\n**Output:** YES or NO.",
    starterCode: `#include<bits/stdc++.h>\nusing namespace std;\nint main(){\n    int n; cin>>n;\n    if(n<2){cout<<"NO";return 0;}\n    for(int i=2;i*i<=n;i++) if(n%i==0){cout<<"NO";return 0;}\n    cout<<"YES";\n    return 0;\n}`,
    testCases: [{ input: "7", expected: "YES" }, { input: "4", expected: "NO" }],
    hints: ["Check divisors up to √n"],
  },
  {
    id: "f-018", track: "fundamentals", difficulty: "easy", points: 10,
    tags: ["strings", "count"],
    title: "Count Vowels",
    description: "Count vowels (a,e,i,o,u) in a lowercase string.\n\n**Input:** A string.\n**Output:** Count of vowels.",
    starterCode: `#include<bits/stdc++.h>\nusing namespace std;\nint main(){\n    string s; cin>>s;\n    int cnt=0;\n    string v="aeiou";\n    for(char c:s) if(v.find(c)!=string::npos) cnt++;\n    cout<<cnt;\n    return 0;\n}`,
    testCases: [{ input: "hello", expected: "2" }, { input: "programming", expected: "3" }],
    hints: ["Check if each char is in 'aeiou'"],
  },
  {
    id: "f-019", track: "fundamentals", difficulty: "medium", points: 20,
    tags: ["arrays", "rotation"],
    title: "Rotate Array Left",
    description: "Left-rotate an array by K positions.\n\n**Input:** N K, then N integers.\n**Output:** Rotated array space-separated.",
    starterCode: `#include<bits/stdc++.h>\nusing namespace std;\nint main(){\n    int n,k; cin>>n>>k;\n    vector<int> a(n);\n    for(auto& x:a) cin>>x;\n    k%=n;\n    rotate(a.begin(),a.begin()+k,a.end());\n    for(auto x:a) cout<<x<<\" \";\n    return 0;\n}`,
    testCases: [{ input: "5 2\n1 2 3 4 5", expected: "3 4 5 1 2 " }],
    hints: ["std::rotate(begin, begin+k, end)"],
  },
  {
    id: "f-020", track: "fundamentals", difficulty: "medium", points: 20,
    tags: ["strings", "manipulation"],
    title: "Word Count",
    description: "Count words in a sentence.\n\n**Input:** A line of text.\n**Output:** Word count.",
    starterCode: `#include<bits/stdc++.h>\nusing namespace std;\nint main(){\n    string line; getline(cin,line);\n    istringstream ss(line);\n    string word; int cnt=0;\n    while(ss>>word) cnt++;\n    cout<<cnt;\n    return 0;\n}`,
    testCases: [{ input: "hello world foo", expected: "3" }],
    hints: ["Use istringstream to split on spaces"],
  },
  {
    id: "f-021", track: "fundamentals", difficulty: "medium", points: 20,
    tags: ["math", "gcd"],
    title: "GCD and LCM",
    description: "Compute GCD and LCM of two numbers.\n\n**Input:** Two integers a b.\n**Output:** GCD LCM on one line.",
    starterCode: `#include<bits/stdc++.h>\nusing namespace std;\nint main(){\n    long long a,b; cin>>a>>b;\n    long long g=__gcd(a,b);\n    cout<<g<<\" \"<<(a/g)*b;\n    return 0;\n}`,
    testCases: [{ input: "12 18", expected: "6 36" }, { input: "7 5", expected: "1 35" }],
    hints: ["LCM = (a/gcd)*b"],
  },
  {
    id: "f-022", track: "fundamentals", difficulty: "hard", points: 30,
    tags: ["recursion", "backtracking"],
    title: "N-Queens Count",
    description: "Count the number of valid N-Queens configurations.\n\n**Input:** N.\n**Output:** Number of solutions.",
    starterCode: `#include<bits/stdc++.h>\nusing namespace std;\nint n, cnt=0;\nvector<int> col, diag1, diag2;\nvoid solve(int row){\n    if(row==n){cnt++;return;}\n    for(int c=0;c<n;c++){\n        if(col[c]||diag1[row-c+n-1]||diag2[row+c]) continue;\n        col[c]=diag1[row-c+n-1]=diag2[row+c]=1;\n        solve(row+1);\n        col[c]=diag1[row-c+n-1]=diag2[row+c]=0;\n    }\n}\nint main(){\n    cin>>n;\n    col.assign(n,0); diag1.assign(2*n,0); diag2.assign(2*n,0);\n    solve(0);\n    cout<<cnt;\n    return 0;\n}`,
    testCases: [{ input: "4", expected: "2" }, { input: "8", expected: "92" }],
    hints: ["Track columns and both diagonals", "Backtrack when conflict found"],
  },
  {
    id: "f-023", track: "fundamentals", difficulty: "hard", points: 30,
    tags: ["pointers", "dynamic memory"],
    title: "Dynamic Array Operations",
    description: "Create a dynamic int array of size N, fill with squares, find max.\n\n**Input:** N.\n**Output:** All squares then max, each on separate lines.",
    starterCode: `#include<bits/stdc++.h>\nusing namespace std;\nint main(){\n    int n; cin>>n;\n    int* arr = new int[n];\n    for(int i=0;i<n;i++) arr[i]=(i+1)*(i+1);\n    for(int i=0;i<n;i++) cout<<arr[i]<<\"\\n\";\n    cout<<*max_element(arr,arr+n)<<\"\\n\";\n    delete[] arr;\n    return 0;\n}`,
    testCases: [{ input: "4", expected: "1\n4\n9\n16\n16" }],
    hints: ["new int[n] allocates on heap", "delete[] to free"],
  },
  // OOP extras
  {
    id: "o-009", track: "oop", difficulty: "easy", points: 10,
    tags: ["classes", "static"],
    title: "Static Member Counter",
    description: "Track total object instances using a static member.\n\n**Input:** N (number of objects to create).\n**Output:** Total count after creation.",
    starterCode: `#include<bits/stdc++.h>\nusing namespace std;\nclass Widget{\n    static int count;\npublic:\n    Widget(){ count++; }\n    static int getCount(){ return count; }\n};\nint Widget::count=0;\nint main(){\n    int n; cin>>n;\n    vector<Widget> v(n);\n    cout<<Widget::getCount();\n    return 0;\n}`,
    testCases: [{ input: "5", expected: "5" }],
    hints: ["Static members are shared across all instances"],
  },
  {
    id: "o-010", track: "oop", difficulty: "medium", points: 20,
    tags: ["copy constructor"],
    title: "Deep Copy vs Shallow Copy",
    description: "Implement a class with a deep-copy constructor. Modify copy and verify original unchanged.\n\n**Input:** Array values and a change index and new value.\n**Output:** Original value at index after copy is modified.",
    starterCode: `#include<bits/stdc++.h>\nusing namespace std;\nclass MyArr{\npublic:\n    int* data; int n;\n    MyArr(int sz):n(sz){ data=new int[n]; for(int i=0;i<n;i++) data[i]=i+1; }\n    MyArr(const MyArr& o):n(o.n){ data=new int[n]; for(int i=0;i<n;i++) data[i]=o.data[i]; }\n    ~MyArr(){ delete[] data; }\n};\nint main(){\n    int n,idx,val; cin>>n>>idx>>val;\n    MyArr a(n);\n    MyArr b(a); // deep copy\n    b.data[idx]=val;\n    cout<<a.data[idx];\n    return 0;\n}`,
    testCases: [{ input: "5 2 99", expected: "3" }],
    hints: ["Deep copy: allocate new memory", "Modifying copy shouldn't affect original"],
  },
  {
    id: "o-011", track: "oop", difficulty: "hard", points: 30,
    tags: ["abstract", "interface"],
    title: "Abstract Payment System",
    description: "Design Payment abstract class with process() and fee(). CreditCard fee=2%, Cash fee=0%. Print net amount.\n\n**Input:** type (credit/cash) and amount.\n**Output:** amount - fee(amount) to 2dp.",
    starterCode: `#include<bits/stdc++.h>\nusing namespace std;\nclass Payment{\npublic:\n    virtual double fee(double amt)=0;\n    double process(double amt){ return amt-fee(amt); }\n    virtual ~Payment(){}\n};\nclass CreditCard:public Payment{ public: double fee(double a){ return a*0.02; } };\nclass Cash:public Payment{ public: double fee(double){ return 0; } };\nint main(){\n    string t; double amt; cin>>t>>amt;\n    Payment* p = t=="credit"?new CreditCard():new Cash();\n    cout<<fixed<<setprecision(2)<<p->process(amt)<<\"\\n\";\n    delete p; return 0;\n}`,
    testCases: [{ input: "credit 100", expected: "98.00" }, { input: "cash 100", expected: "100.00" }],
    hints: ["CreditCard deducts 2%", "Cash has no fee"],
  },
  // DSA extras
  {
    id: "d-013", track: "dsa", difficulty: "easy", points: 10,
    tags: ["arrays", "sliding window"],
    title: "Maximum Subarray (Kadane's)",
    description: "Find the maximum sum contiguous subarray.\n\n**Input:** N, then N integers.\n**Output:** Maximum subarray sum.",
    starterCode: `#include<bits/stdc++.h>\nusing namespace std;\nint main(){\n    int n; cin>>n;\n    vector<int> a(n);\n    for(auto& x:a) cin>>x;\n    int maxSum=a[0], cur=a[0];\n    for(int i=1;i<n;i++){\n        cur=max(a[i],cur+a[i]);\n        maxSum=max(maxSum,cur);\n    }\n    cout<<maxSum;\n    return 0;\n}`,
    testCases: [{ input: "8\n-2 1 -3 4 -1 2 1 -5 4", expected: "6" }],
    hints: ["Kadane's: extend or restart subarray at each step"],
  },
  {
    id: "d-014", track: "dsa", difficulty: "medium", points: 20,
    tags: ["graph", "dfs"],
    title: "Number of Connected Components",
    description: "Count connected components in an undirected graph.\n\n**Input:** N nodes, M edges, then M pairs.\n**Output:** Number of components.",
    starterCode: `#include<bits/stdc++.h>\nusing namespace std;\nvector<vector<int>> adj;\nvector<bool> vis;\nvoid dfs(int u){ vis[u]=true; for(int v:adj[u]) if(!vis[v]) dfs(v); }\nint main(){\n    int n,m; cin>>n>>m;\n    adj.resize(n); vis.assign(n,false);\n    for(int i=0;i<m;i++){int u,v;cin>>u>>v;adj[u].push_back(v);adj[v].push_back(u);}\n    int cnt=0;\n    for(int i=0;i<n;i++) if(!vis[i]){dfs(i);cnt++;}\n    cout<<cnt;\n    return 0;\n}`,
    testCases: [{ input: "5 3\n0 1\n1 2\n3 4", expected: "2" }],
    hints: ["DFS from each unvisited node = new component"],
  },
  {
    id: "d-015", track: "dsa", difficulty: "medium", points: 20,
    tags: ["dp", "coin change"],
    title: "Coin Change (Min Coins)",
    description: "Find minimum coins to make amount. Return -1 if impossible.\n\n**Input:** N coins, then N values, then amount.\n**Output:** Min coins or -1.",
    starterCode: `#include<bits/stdc++.h>\nusing namespace std;\nint main(){\n    int n; cin>>n;\n    vector<int> coins(n);\n    for(auto& c:coins) cin>>c;\n    int amt; cin>>amt;\n    vector<int> dp(amt+1,INT_MAX);\n    dp[0]=0;\n    for(int i=1;i<=amt;i++) for(int c:coins) if(c<=i&&dp[i-c]!=INT_MAX) dp[i]=min(dp[i],dp[i-c]+1);\n    cout<<(dp[amt]==INT_MAX?-1:dp[amt]);\n    return 0;\n}`,
    testCases: [{ input: "3\n1 5 6\n11", expected: "2" }, { input: "2\n3 5\n7", expected: "-1" }],
    hints: ["dp[i] = min coins for amount i"],
  },
  {
    id: "d-016", track: "dsa", difficulty: "hard", points: 30,
    tags: ["trees", "level order"],
    title: "Level Order Traversal",
    description: "Print binary tree level-by-level. Build tree from input as parent-child pairs.\n\n**Input:** N nodes, then N-1 pairs (parent child direction L/R), then query for level count.\n**Output:** Level order, levels separated by |.",
    starterCode: `#include<bits/stdc++.h>\nusing namespace std;\nstruct Node{ int val; Node *l=nullptr,*r=nullptr; Node(int v):val(v){} };\nint main(){\n    int n; cin>>n;\n    map<int,Node*> nodes;\n    for(int i=1;i<=n;i++) nodes[i]=new Node(i);\n    int root=1;\n    for(int i=0;i<n-1;i++){\n        int p,c; char d; cin>>p>>c>>d;\n        if(d=='L') nodes[p]->l=nodes[c];\n        else nodes[p]->r=nodes[c];\n    }\n    queue<Node*> q; q.push(nodes[root]);\n    bool first=true;\n    while(!q.empty()){\n        int sz=q.size();\n        if(!first) cout<<\"|\";\n        first=false;\n        while(sz--){\n            auto nd=q.front();q.pop();\n            cout<<nd->val<<\" \";\n            if(nd->l) q.push(nd->l);\n            if(nd->r) q.push(nd->r);\n        }\n    }\n    return 0;\n}`,
    testCases: [{ input: "5\n1 2 L\n1 3 R\n2 4 L\n2 5 R", expected: "1 |2 3 |4 5 " }],
    hints: ["BFS for level order", "Use queue, process level by level"],
  },
  {
    id: "d-017", track: "dsa", difficulty: "easy", points: 10,
    tags: ["sorting", "merge sort"],
    title: "Merge Sort",
    description: "Implement merge sort and print sorted array.\n\n**Input:** N, then N integers.\n**Output:** Sorted array space-separated.",
    starterCode: `#include<bits/stdc++.h>\nusing namespace std;\nvoid merge(vector<int>& a,int l,int m,int r){\n    vector<int> tmp;\n    int i=l,j=m+1;\n    while(i<=m&&j<=r) a[i]<=a[j]?tmp.push_back(a[i++]):tmp.push_back(a[j++]);\n    while(i<=m) tmp.push_back(a[i++]);\n    while(j<=r) tmp.push_back(a[j++]);\n    for(int k=l;k<=r;k++) a[k]=tmp[k-l];\n}\nvoid msort(vector<int>& a,int l,int r){ if(l<r){int m=(l+r)/2;msort(a,l,m);msort(a,m+1,r);merge(a,l,m,r);} }\nint main(){\n    int n; cin>>n;\n    vector<int> a(n); for(auto& x:a) cin>>x;\n    msort(a,0,n-1);\n    for(auto x:a) cout<<x<<\" \";\n    return 0;\n}`,
    testCases: [{ input: "6\n5 2 8 1 9 3", expected: "1 2 3 5 8 9 " }],
    hints: ["Divide into halves, sort each, merge"],
  },
  {
    id: "d-018", track: "dsa", difficulty: "medium", points: 20,
    tags: ["dp", "longest increasing subsequence"],
    title: "Longest Increasing Subsequence",
    description: "Find the length of LIS in an array.\n\n**Input:** N, then N integers.\n**Output:** LIS length.",
    starterCode: `#include<bits/stdc++.h>\nusing namespace std;\nint main(){\n    int n; cin>>n;\n    vector<int> a(n); for(auto& x:a) cin>>x;\n    vector<int> dp(n,1);\n    for(int i=1;i<n;i++) for(int j=0;j<i;j++) if(a[j]<a[i]) dp[i]=max(dp[i],dp[j]+1);\n    cout<<*max_element(dp.begin(),dp.end());\n    return 0;\n}`,
    testCases: [{ input: "6\n3 10 2 1 20 4", expected: "3" }],
    hints: ["dp[i] = length of LIS ending at index i"],
  },
  {
    id: "d-019", track: "dsa", difficulty: "hard", points: 30,
    tags: ["graph", "dijkstra"],
    title: "Dijkstra's Shortest Path",
    description: "Find shortest path from node 0 to all nodes.\n\n**Input:** N nodes, M weighted edges, then M triples u v w.\n**Output:** Distances from 0, space-separated (-1 if unreachable).",
    starterCode: `#include<bits/stdc++.h>\nusing namespace std;\ntypedef pair<int,int> pii;\nint main(){\n    int n,m; cin>>n>>m;\n    vector<vector<pii>> adj(n);\n    for(int i=0;i<m;i++){int u,v,w;cin>>u>>v>>w;adj[u].push_back({v,w});adj[v].push_back({u,w});}\n    vector<int> dist(n,INT_MAX); dist[0]=0;\n    priority_queue<pii,vector<pii>,greater<>> pq; pq.push({0,0});\n    while(!pq.empty()){\n        auto[d,u]=pq.top();pq.pop();\n        if(d>dist[u]) continue;\n        for(auto[v,w]:adj[u]) if(dist[u]+w<dist[v]){dist[v]=dist[u]+w;pq.push({dist[v],v});}\n    }\n    for(int i=0;i<n;i++) cout<<(dist[i]==INT_MAX?-1:dist[i])<<\" \";\n    return 0;\n}`,
    testCases: [{ input: "4 5\n0 1 1\n0 2 4\n1 2 2\n1 3 5\n2 3 1", expected: "0 1 3 4 " }],
    hints: ["Min-heap priority queue", "Relax edges when shorter path found"],
  },
  {
    id: "d-020", track: "dsa", difficulty: "hard", points: 30,
    tags: ["union find"],
    title: "Minimum Spanning Tree (Kruskal's)",
    description: "Find MST weight using Kruskal's algorithm.\n\n**Input:** N nodes, M edges, then M triples u v w.\n**Output:** MST total weight.",
    starterCode: `#include<bits/stdc++.h>\nusing namespace std;\nstruct DSU{ vector<int> p,r; DSU(int n):p(n),r(n,0){iota(p.begin(),p.end(),0);} int find(int x){return p[x]==x?x:p[x]=find(p[x]);} bool unite(int a,int b){a=find(a);b=find(b);if(a==b)return false;if(r[a]<r[b])swap(a,b);p[b]=a;if(r[a]==r[b])r[a]++;return true;} };\nint main(){\n    int n,m; cin>>n>>m;\n    vector<tuple<int,int,int>> edges;\n    for(int i=0;i<m;i++){int u,v,w;cin>>u>>v>>w;edges.push_back({w,u,v});}\n    sort(edges.begin(),edges.end());\n    DSU dsu(n); int mst=0;\n    for(auto[w,u,v]:edges) if(dsu.unite(u,v)) mst+=w;\n    cout<<mst;\n    return 0;\n}`,
    testCases: [{ input: "4 5\n0 1 1\n0 2 4\n1 2 2\n1 3 5\n2 3 1", expected: "4" }],
    hints: ["Sort edges by weight", "Use Union-Find to avoid cycles"],
  },
];

// Combined export — all 50+ problems
export const ALL_PROBLEMS: Problem[] = [...PROBLEMS, ...EXTRA_PROBLEMS];
